default: &default
  runner:
    instances: 1
    input_queue: "svp"
    input_correction_queue: "svp_redis_correction"
    output_queue: "svp_billing"

default_database: &default_database
  adapter: postgresql
  encoding: utf8

default_rabbit: &default_rabbit
  port: 5672

development:
  <<: *default

  database:
    <<: *default_database

    host: localhost
    port: 5432
    database: svpdb1
    username: test_usr_dev1
    password: test_usr_dev1

  rabbit:
    <<: *default_rabbit
    host: 'localhost'  
    user: 'guest'
    password: 'guest'

  redis_cache:
    host: localhost
    port: 6379
    prefix: svp_cache

  remote_syslog:
    host: '0.0.0.0'
    port: 514

test:
  runner:
    instances: 1
    input_queue: "svp_test"
    input_correction_queue: "svp_redis_correction_test"
    output_queue: "svp_billing_test"

  database:
    <<: *default_database

    host: 172.17.10.34
    port: 5432
    database: svpdb_test
    username: svp
    password: qir29sir

  rabbit:
    <<: *default_rabbit
    host: '172.17.10.34'  
    user: 'svp_app'
    password: 'svp_app'

  redis_cache:
    host: 172.17.10.34
    port: 6379
    prefix: svp_cache

  remote_syslog:
    host: '172.17.10.41'
    port: 514


production:
  <<: *default

  database:
    <<: *default_database

    # host: 172.17.10.24
    host: '10.0.1.132'
    port: 5432
    database: svpdb
    username: svp
    password: qir29sir

  rabbit:
    <<: *default_rabbit
    host: '10.0.1.200' 
    user: 'billing'
    password: 'fe5jaepein7poqu7iegheeNgeTahb8ae'
    vhost: 'billing'

  redis_cache:
    host: '10.0.1.132'
    port: 6379
    db: 4
    prefix: svp_cache

  remote_syslog:
    host: '10.0.1.200'
    port: 514
    disable: 1