default: &default
  runner:
    instances: 1
    input_queue: "svp"
    output_queue: "svp_billing"

default_database: &default_database
  adapter: postgresql
  encoding: utf8

development:
  <<: *default

  database:
    <<: *default_database

    host: localhost
    port: 5432
    database: svpdb1
    username: test_usr_dev1
    password: test_usr_dev1

  redis_cache:
    host: localhost
    port: 6379

test:
  <<: *default

  database:
    <<: *default_database


production:
  <<: *default

  database:
    <<: *default_database

    host: 172.17.10.24
    port: 5432
    database: svpdb
    username: svp
    password: qir29sir

  redis_cache:
    host: 172.17.10.27
    port: 6379